SET @person_firstname := 'Владимир';
SET @person_lastname := '';
SET @person_middlename := '';
SET @username = 'mkhokhlach';
SET @person_photo := CONCAT('/images/persons_photos/photo.', @username, '.jpg');
SET @user_email := CONCAT(@username, '@rassprof.ru');
SET @user_password := 'abc';
SET @user_authorization_level := 'employee';
SET @user_terminal_username := @username;
SET @employee_date_started := '2021-01-11 08:00:00';
SET @department_name := 'Маркетинг';
SET @role_name = 'Маркетолог';
SET @role_rate = '1.00';
SET @duties_dir = '';
SET @duties_ext = '.pdf';
SET @duties = '';
START TRANSACTION;
INSERT INTO `persons` (`firstname`, `lastname`, `middlename`, `photo`, `date_created`) VALUES (@person_firstname, @person_lastname, @person_middlename, @person_photo, NOW());
SELECT @person_id:=LAST_INSERT_ID();
INSERT INTO `users` (`email`, `password`, `avatar`, `date_created`, `date_last_activity`, `status`, `authorization_level`, `terminal_username`, `person_id`) VALUES (@user_email, MD5(@user_password), NULL, NOW(), NULL, NULL, @user_authorization_level, @user_terminal_username, @person_id);
SELECT @user_id:=LAST_INSERT_ID();
INSERT INTO `employees` (`person_id`, `date_started`) VALUES(@person_id, @employee_date_started);
SELECT @employee_id:=LAST_INSERT_ID();
SELECT @department_id:=`id` FROM `departments` WHERE `name` = @department_name;
INSERT INTO `roles` (`department_id`, `name`, `employee_id`, `rate`, `duties`) VALUES (@department_id, @role_name, @employee_id, @role_rate, @duties);
COMMIT;